spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wlqyanyalun008++

mybatis:
  type-aliases-package: com.quanquan.dto